# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title:  🦊 corgijans blog 
email: jan.vaorin@tu-dortmund.de
description: >- # this means to ignore newlines until "baseurl:"
  corgijans awsome blog about Corgis and computer science
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
# Build settings
theme: beautiful-jekyll-theme
plugins:
  - jekyll-feed
site:
  exclude-ads: true

navbar-links:
  home: "index"
  about me: "aboutme"
  projects: "projects"
  #Resources:
  #  - Learn markdown: "https://www.markdowntutorial.com/"
  Author's home: "https://www.corgijan.dev"
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
#
avatar: "https://avatars.githubusercontent.com/u/70795482?v=4"


# Select the social network links that you want to show in the footer.
# You can change the order that they show up on the page by changing the order here.
# Uncomment the links you want to show and add your information to each one.
social-network-links:
  email: "someone@example.com"
  #rss: true  # remove this line if you don't want to show an RSS link at the bottom
  #facebook: deanattali
  github: corgijan
    #twitter: daattali
    #patreon: DeanAttali
    #youtube: "@daattali"
    #whatsapp: 15551212
#  medium: yourname
#  reddit: yourname
#  linkedin: daattali
#  xing: yourname
#  stackoverflow: "3943160/daattali"
#  snapchat: deanat78
#  instagram: deanat78
#  spotify: yourname
#  telephone: +14159998888
#  steam: deanat78
#  twitch: yourname
#  yelp: yourname
#  telegram: yourname
#  calendly: yourname
#  mastodon: instance.url/@username
#  bluesky: yourname
#  ORCID: your ORCID ID
#  google-scholar: your google scholar
#  discord: "invite_code" or "users/userid" or "invite/invite_code" 
#  kaggle: yourname
#  hackerrank: yourname
#  gitlab: yourname
#  itchio: yourname
#  untappd: yourname
#
url-pretty: "blog.corgijan.com"

# Personalize the colours in your website. Colour values can be any valid CSS colour
#

page-col: "rgb(48,52,54)"             # Dark Gray
text-col: "#CCCCCC"             # Light Gray
link-col: "#008AFF"             # Blue
hover-col: "#0085A1"            # Light Blue
navbar-col: "#303030"           # Dark Gray
navbar-text-col: "#CCCCCC"      # Light Gray
navbar-border-col: "#666666"    # Medium Gray
footer-col: "#303030"           # Dark Gray
footer-text-col: "#CCCCCC"      # Light Gray
footer-link-col: "#008AFF"      # Blue
footer-hover-col: "#0085A1"     # Light Blue
