version: '3.7'

services:

  jekyll:
    image: bretfisher/jekyll-serve
    environment:
      JEKYLL_UID: 1000
      JEKYLL_GID: 1000
    command: sh -c "JEKYLL_ENV=production bundle exec jekyll build --trace"
    volumes:
      - .:/site:z

  nginx:
    image: nginx
    restart: always
    volumes:
      - ./_site:/usr/share/nginx/html
      - ./config.nginx:/etc/nginx/conf.d/default.conf
    ports:
      - "11001:80"
    depends_on:
      - jekyll
    command: /bin/sh -c "nginx -g 'daemon off;'"
