version: '3.7'

services:

  jekyll:
    image: bretfisher/jekyll-serve
    command: sh -c "JEKYLL_ENV=production bundle exec jekyll build --trace"
    volumes:
      - .:/site

 nginx:
    image: nginx
    volumes:
      - ./_site:/usr/share/nginx/html
      - ./_site/404.html:/usr/share/nginx/html/404.html
    ports:
      - "11001:80"
    depends_on:
      - jekyll
    command: /bin/sh -c "nginx -g 'daemon off;'"